# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: apiKey
  value: initialValue 

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: echo "Hello, $QC_API_KEY"
  displayName: 'Run a one-line script'
  env:
    BUILD_DIRECTORY: $(Agent.BuildDirectory)
    QC_API_KEY: $(apiKey)

- script: docker run --user root --network=host -v $BUILD_DIRECTORY:/src/:rw  -e QC_API_KEY=$QC_API_KEY -e diff_mode=1 -e BRANCH=test-pr -t qualityclouds/pipeline-salesforce sf-scan
  displayName: 'Scan'
  env:
    BUILD_DIRECTORY: $(Agent.BuildDirectory)
    QC_API_KEY: $(apiKey)
